FROM cyberlab-network:latest

ENV DEBIAN_FRONTEND=noninteractive

# Serveur DNS pour le lab dns
RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
    bind9 \
    bind9utils \
    dnsmasq \
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
